language: R
sudo: false
cache:
  packages: true
  directories:
  - _book

pandoc_version: 1.17.2

before_install:
- mkdir ~/.R
- cp Makevars ~/.R

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJYY6UT5EHUXEKWCA
  secret_access_key:
    secure: "Ogjfu+wBbKDtY1VJQnfGejNcxPx2iEwlSgEeTHC7M5jyuSIdYdaf0IbJ9LlDSxA/vcO/NbGOzEdPKevuiRgcU7Bj+J7tlOrvw6WC4R1RK4JQNowuxoDOwNlAvPD5O5DMiIwku+xbjcxyIwU1yPWIjCgpOmAAHMgBeYI+4+N9Ggk="
  bucket: adv-r.hadley.nz
  local-dir: _book
  region: us-west-1
